# Copyright (c) 2012 by Cisco Systems, Inc.

.PHONY: all
all: a b

# This will store 'aaa' as the value of 'string'
a:
	./app-inst aaa

# This will store 'bbb' as the value of 'string'
b:
	./app-inst bbb
