#!/usr/bin/env python

# Copyright (c) 2012 by Cisco Systems, Inc.

import unittest

import sys
import os
import unittest

# Import each unit test module
from utlib.ut_appinst import appinstTests
from utlib.ut_env import envTests
from utlib.ut_simple import simpleTests
from utlib.ut_shell import shellTests

def main():
    unittest.main(verbosity=2)

if __name__ == "__main__":
    main()
