#!/usr/bin/env python

# Copyright (c) 2012 by Cisco Systems, Inc.

import unittest

import sys
import os
import unittest

# Import each unit test module
from utlib.appinst import appinstTests
from utlib.env import envTests
from utlib.simple import simpleTests
from utlib.shell import shellTests
from utlib.cli import CliTest

def main():
    unittest.main(verbosity=2)

if __name__ == "__main__":
    main()
